### ISSUE TITLE
ValList.txt missing for online test 

### ISSUE THREAD

**Issue by prabinaneupane** [GibranBenitez/IPN-hand#2]
@GibranBenitez 
While doing online test of the dataset I get the following error 
![image](https://user-images.githubusercontent.com/62377115/98202509-b9d70800-1f64-11eb-8a8a-26e28d442d71.png)

It is caused due to the following line in online_test.py
elif opt.dataset == 'ipn':
    file_set = os.path.join(opt.video_path, 'ValList.txt')
    test_paths = []
    buf = 0
    with open(file_set,'rb') as f:
        for line in f:
            vid_name = line.decode().split('\t')[0]
            test_paths.append(os.path.join(opt.video_path, 'frames', vid_name))

However I could not find this file anywhere in your drive or the repo. Could you please provide this file. Is it the same as the vallistall.txt file in the annotation_ipn directory

**Comment by GibranBenitez** [comment]
Hi, I am sorry for my very late reply.
I have fixed the problem with [__this commit__](https://github.com/GibranBenitez/IPN-hand/commit/52f26d88be1b2bfad70571389ec857d35f675c2e)

In addition, the file you are searching for is now `'Video_TestList.txt'` and you can find it [here](https://drive.google.com/drive/u/2/folders/1-mihJEIFoNDpfo1puF8xAMJz6PGVKsBD), on the [official project](https://gibranbenitez.github.io/IPN_Hand/) page of the dataset.

**Comment by prabinaneupane** [comment]
Thank you so much for the help. I can now run online test successfully. I have another question, did you do real time classification on the video as shown in the official project page?

**Comment by GibranBenitez** [comment]
HI again,

That video is only for visualization purposes. 
All the process was made offline. 

Please don't forget to consider the IO time for testing online, which was not included in the reported inference time. 
And, of course, your pull request is always welcome.

**Comment by prabinaneupane** [comment]
Thank you for the suggestion. 
I will consider IO time  for the testing. Also could you share the pretrained model of semantic segmentation. I am trying to convert the RGB video to segmented videos for the real time test.

**Comment by prabinaneupane** [comment]
@GibranBenitez I am trying to do real time classification with semantic segmentation. Could you please provide the training details you used to convert the frames into segment. I have seen the HardNet model that you used for training purposes. But could provide some more details?
1. Did you use the pretrained model provided by the authors of the HardNet paper implementation.
2. The **Rendered Handpose Dataset** you mentioned that you used for implementing segmentation has three **folders, mask, color and depth**. Which one did you use?
3. Could you please provide the configurations you used? I have only been able to figure out that you used binary mask at 320x240. 

Thank you very much
