### ISSUE TITLE
in dataset.py "from datasets.egogesture import EgoGesture" No module named 'datasets.egogesture'

### ISSUE THREAD

**Issue by jackeycheng88** [GibranBenitez/IPN-hand#3]
hello, i can not find egogesture.py in the folder datasets. should i delete the code "from datasets.egogesture import EgoGesture" ?

**Comment by prabinaneupane** [comment]
I think you can just comment that out, it did it and it worked for me.

**Comment by GibranBenitez** [comment]
Thanks for the quick reply @prabinaneupane!
I have fixed the problem in the `dataset.py` file -> 0b061e4438f159e3e312af4959cb424917b5c367

I am closing this issue since the direct problem is solved.
